### ISSUE TITLE
Rescue from Parslet::ParseFailed?

### ISSUE THREAD

**Issue by jkeck** [projectblacklight/blacklight_advanced_search#27]
We get a lot of `Parslet::ParseFailed` errors thrown from crawlers putting random input into the adv. search form.  Should BlacklightAdvancedSearch rescue from this error or should it be up to the application to make a determination of what they would like to do?

**Comment by atz** [comment]
I think this is resolved with `@@parslet_failed_exceptions` here:
https://github.com/projectblacklight/blacklight_advanced_search/blob/c7166a975de11aa96876aa2a86bd1fc7ee1c3735/lib/blacklight_advanced_search/advanced_search_builder.rb#L37-L41

Please reopen if the class variable is insufficient (or if you have a better idea, because that is sorta ugly).
